version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: casadocodigo-app
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - appnet
    environment:
      DB_USER: appuser
      DB_PASS: ${BANCO_DE_DADOS_SENHA}
      JDBC_URL_MYSQL: jdbc:mysql://mysql/casadocodigo?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false

  mysql:
    image: mysql:8.3
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: casadocodigo
      MYSQL_USER: appuser
      MYSQL_PASSWORD: ${BANCO_DE_DADOS_SENHA}
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s
      timeout: 10s
      retries: 10

volumes:
  mysql-data:

networks:
  appnet: